#//// Version SIMPLE \\\\\

program: main.c
	@gcc -Wall main.c -o main # @ permet de ne pas afficher la ligne de commande -- echo montrer sur le prompt ce qu'on veut
	@./main

#//// Version ADVANCED \\\\\
COMPILATEUR = gcc
# EXEC = main.x
# SOURCE = main.c
#
# executer : compiler
# 	./$(EXEC)
#
# compiler : $(SOURCE)
# 	gcc -o $(EXEC) $(SOURCE) # ?? A verifier : $(COMPILATEUR) ne fonctionne pas ??
